# Config file for automatic testing at travis-ci.org

language: python

stages:
    - test
    - deploy

jobs:
  include:     
      # python 3.5 only supported till matplotlib 3.0.3 
    - name: "Py3.5 - Linux - Latest - matplotlib=3.0.3"
      python: "3.5"
      os: linux
      before_install: python gen_requirements_ci.py --skip sphinx sphinx_rtd_theme isort flake8 yapf --matplotlib 3.0.3
      install: pip install -r requirements_ci.txt
      script: coverage run --source torchutils -m unittest discover -v

    - name: "Py3.7 - Linux - Latest"
      python: "3.7"
      os: linux
      before_install: python gen_requirements_ci.py --skip sphinx sphinx_rtd_theme isort flake8 yapf
      install: pip install -r requirements_ci.txt
      script: coverage run --source torchutils -m unittest discover -v

    - name: "Py3.7.5 - OSX - Latest"
      osx_image: xcode9.4  # Python 3.7.5 running on macOS 10.13
      language: shell  # 'language: python' is an error on Travis CI macOS
      os: osx
      before_install:
        - python3 --version
        - python3 gen_requirements_ci.py --skip sphinx sphinx_rtd_theme isort flake8 yapf
      install: pip3 install -r requirements_ci.txt
      script: coverage run --source torchutils -m unittest discover -v

      # pillow==7.0.0 does not have PILLOW_VERSION variable.
    - name: "Py3.6 - Linux - torch=1.0.0 torchvision=0.2.1 pillow=6.2.0"
      python: "3.6"
      os: linux
      before_install: python gen_requirements_ci.py --skip sphinx sphinx_rtd_theme isort flake8 yapf --torch 1.0.0 --torchvision 0.2.1 --pillow 6.2.0
      install: pip install -r requirements_ci.txt
      script:
        - coverage run --source torchutils -m unittest discover -v 

    - name: "Py3.6 - Linux - torch=1.1.0 torchvision=0.3.0 pillow=6.2.0"
      python: "3.6"
      os: linux
      before_install: python gen_requirements_ci.py --skip sphinx sphinx_rtd_theme isort flake8 yapf --torch 1.1.0 --torchvision 0.3.0 --pillow 6.2.0
      install: pip install -r requirements_ci.txt
      script:
        - coverage run --source torchutils -m unittest discover -v

    - name: "Py3.6 - Linux - torch=1.2.0 torchvision=0.4.0 pillow=6.2.0"
      python: "3.6"
      os: linux
      before_install: python gen_requirements_ci.py --skip sphinx sphinx_rtd_theme isort flake8 yapf --torch 1.2.0 --torchvision 0.4.0 --pillow 6.2.0
      install: pip install -r requirements_ci.txt
      script:
        - coverage run --source torchutils -m unittest discover -v

    - name: "Py3.6 - Linux - torch=1.3.0 torchvision=0.4.2 pillow=6.2.0"
      python: "3.6"
      os: linux
      before_install: python gen_requirements_ci.py --skip sphinx sphinx_rtd_theme isort flake8 yapf --torch 1.3.0 --torchvision 0.4.2 --pillow 6.2.0
      install: pip install -r requirements_ci.txt
      script:
        - coverage run --source torchutils -m unittest discover -v

    - name: "Py3.6 - Linux - numpy=1.16.2"
      python: "3.6"
      os: linux
      before_install: python gen_requirements_ci.py --skip sphinx sphinx_rtd_theme isort flake8 yapf --numpy 1.16.2
      install: pip install -r requirements_ci.txt
      script:
        - coverage run --source torchutils -m unittest discover -v

    - name: "Py3.6 - Linux - numpy=1.16.4"
      python: "3.6"
      os: linux
      before_install: python gen_requirements_ci.py --skip sphinx sphinx_rtd_theme isort flake8 yapf --numpy 1.16.4
      install: pip install -r requirements_ci.txt
      script:
        - coverage run --source torchutils -m unittest discover -v

    - name: "Py3.6 - Linux - numpy=1.17.2"
      python: "3.6"
      os: linux
      before_install: python gen_requirements_ci.py --skip sphinx sphinx_rtd_theme isort flake8 yapf --numpy 1.17.2
      install: pip install -r requirements_ci.txt
      script:
        - coverage run --source torchutils -m unittest discover -v
        
    - name: "Py3.6 - Linux - numpy=1.17.4"
      python: "3.6"
      os: linux
      before_install: python gen_requirements_ci.py --skip sphinx sphinx_rtd_theme isort flake8 yapf --numpy 1.17.4
      install: pip install -r requirements_ci.txt
      script:
        - coverage run --source torchutils -m unittest discover -v

    # Deploy build for docs
    - name: "Py3.6 - Linux - Latest (with Flake8) (Deploy)"
      stage: deploy
      python: "3.6"
      os: linux
      install: pip install -r requirements.txt
      script:
        # only one test with flake8 is sufficient
        - flake8
        - isort -rc --check-only --diff torchutils/
        - yapf -r -d --style .style.yapf torchutils/
        - coverage run --source torchutils -m unittest discover -v
        - cd docs/
        - make html
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      deploy:
        provider: pages     # deploy to github page
        skip_cleanup: true
        local_dir: docs/_build/html
        github_token: $GITHUB_TOKEN     # set in travis-ci.org dashboard        